### ISSUE TITLE
`Error: Cannot find module` after using the binary normally

### ISSUE THREAD

**Issue by italodeandra** [leafac/caxa#52]
I can use the binary normally after compiling it, but if I close it and open after some time (if I just reopen it will still work), it will show this error:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './xhr-sync-worker.js'
Require stack:
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\node_modules\jsdom\lib\jsdom\living\xhr\XMLHttpRequest-impl.js
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\node_modules\jsdom\lib\jsdom\living\generated\XMLHttpRequest.js
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\node_modules\jsdom\lib\jsdom\living\interfaces.js
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\node_modules\jsdom\lib\jsdom\browser\Window.js
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\node_modules\jsdom\lib\api.js
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\dist\src\bjShare\BjShare.js
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\dist\src\queue\workers\lookForNewProspectsOnBjShare.worker.js
- C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\dist\server\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\node_modules\jsdom\lib\jsdom\living\xhr\XMLHttpRequest-impl.js:31:50)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Italo\AppData\Local\Temp\caxa\applications\trackfy-agent\kuyponmawv\0\node_modules\jsdom\lib\jsdom\living\generated\XMLHttpRequest.js:655:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\node_modules\\jsdom\\lib\\jsdom\\living\\xhr\\XMLHttpRequest-impl.js',
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\node_modules\\jsdom\\lib\\jsdom\\living\\generated\\XMLHttpRequest.js',
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\node_modules\\jsdom\\lib\\jsdom\\living\\interfaces.js',
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\node_modules\\jsdom\\lib\\jsdom\\browser\\Window.js',
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\node_modules\\jsdom\\lib\\api.js',
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\dist\\src\\bjShare\\BjShare.js',
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\dist\\src\\queue\\workers\\lookForNewProspectsOnBjShare.worker.js',
    'C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent\\kuyponmawv\\0\\dist\\server\\index.js'
  ]
}
```

My solution then is to delete the temp folder `C:\\Users\\Italo\\AppData\\Local\\Temp\\caxa\\applications\\trackfy-agent` so I can use it once more. But the error repeats every time.

So it goes like this:

1 - I open the binary for the first time, use it normally.
2 - I then close it for the day.
3 - The next day, this error shows up.
4 - I delete the temp folder, and we go back to step 1.

**Comment by leafac** [comment]
Hi @italodeandra,

Thanks for reaching out and I’m sorry you’re running into this issue. It seems to be the same as https://github.com/leafac/caxa/issues/37, can you please confirm that? Do you think you can contribute to the solution?

Best.

**Comment by italodeandra** [comment]
Hey @leafac,

Yes, it is the same issue. I'll check what I can do. It's nice to find some investigation already.

You may close this one as a duplicate.
